# Generated by Django 5.1 on 2024-10-03 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='product_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_app.color', verbose_name='Продукт'),
        ),
    ]
